# Generated by Django 4.1.3 on 2023-03-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaction",
            name="vaction_length",
            field=models.FloatField(db_column="date"),
        ),
    ]
