# Generated by Django 4.1.3 on 2023-07-20 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Department")),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="姓名")),
                ("password", models.CharField(max_length=64, verbose_name="密碼")),
                ("age", models.IntegerField(verbose_name="年齡")),
                (
                    "account",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, max_length=10, verbose_name="帳目"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "male"), (2, "female")], verbose_name="gender"
                    ),
                ),
                (
                    "depart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.department",
                        verbose_name="department_id",
                    ),
                ),
            ],
        ),
    ]
