# Generated by Django 4.1.3 on 2023-07-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="account",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="餘額"
            ),
        ),
    ]
