# Generated by Django 4.1.3 on 2023-07-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_alter_department_title_alter_userinfo_create_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrettyNum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=10, verbose_name="手機號")),
                (
                    "price",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="價格"
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "1級"), (2, "2級"), (3, "3級"), (4, "4級")],
                        verbose_name="級別",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "正常"), (2, "停用")], default=2, verbose_name="狀態"
                    ),
                ),
            ],
        ),
    ]
