# Generated by Django 4.1.3 on 2023-03-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="apartment",
            fields=[
                (
                    "apartment_name",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("apartment_information", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "emp_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "apartment_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.apartment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="vaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaction_start", models.DateField()),
                ("vaction_end", models.DateField()),
                ("vaction_length", models.FloatField()),
                (
                    "emp_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="table.employee"
                    ),
                ),
            ],
        ),
    ]
