# Generated by Django 4.1.3 on 2023-03-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaction",
            name="vaction_length",
            field=models.CharField(db_column="date", max_length=4),
        ),
    ]
